openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /user:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1user"
  /login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1login"
  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"
  /movies:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies"
  /movies/{movie}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /quotes:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /quotes/{quote}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /comments:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /notifications:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
